# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Adaptainfra
                                 A QGIS plugin
 Adaptainfra for Qgis with all kind of info
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-08
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Mateus Melo Siqueira/GIZ

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Adaptainfra class from file ADAPTAINFRA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .adaptainfra import ADAPTAINFRA
    return ADAPTAINFRA(iface)
