# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Adaptainfra

 Adaptainfra Plugin for Qgis with all kind of info
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-08
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Mateus Melo Siqueira/GIZ
        email                : mateus.melo@giz.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtWidgets import QToolButton, QMenu, QLineEdit, QLabel, QDialog, QPushButton, QCheckBox, QGridLayout
from qgis.PyQt.QtCore import QObject, Qt, QSize, QUrl
from qgis.PyQt.QtGui import QIcon, QDesktopServices 
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsWkbTypes, QgsGeometry, QgsPoint, QgsProject, QgsMapLayerProxyModel
from qgis.gui import QgsRubberBand, QgsMapLayerComboBox, QgsFieldComboBox
from PyQt5.QtWidgets import QTabWidget, QFrame,QAbstractItemView,  QMessageBox, QShortcut, QDockWidget, QComboBox, QLineEdit, QTableWidget, QTableWidgetItem, QCheckBox, QGridLayout,QVBoxLayout, QLabel, QWidget, QSizePolicy,QSpacerItem, QPushButton
from qgis.PyQt.QtCore import Qt, QSize
from qgis.PyQt.QtGui import QColor, QCursor, QPixmap, QIcon, QImage, QMovie
from PyQt5.QtCore import QThread, pyqtSignal
import base64
import io
from PIL import Image, ImageQt
from functools import partial
from .mods.geosustentability.geosustentability import GEOSUSTENTABILITY
from .mods.about.about_dialog import ABOUTDialog
from .mods.translate.translate import TRANSLATE
from .resources import *
# Import the code for the dialog
import os.path
import time




class Worker(QThread):
    def __init__(self, plugin_dir,iface):
        QThread.__init__(self)
        self.stp = False
        self.plugin_dir = plugin_dir
        self.iface = iface
    up_list = pyqtSignal(list)

    def run(self):
        if not self.stp:
            pass



class ADAPTAINFRA:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory#
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ADAPTAINFRA{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.translate_module()


        
        # Declare instance attributes
        self.actions = []

        self.toolbar = self.iface.addToolBar(u'ADAPTAINFRA')
        self.toolbar.setObjectName(u'adaptainfra_bar')
        self.toolbar.setFixedHeight(40)
        self.toolbar.setIconSize(QSize(35, 35))

        #self.menu = self.tr(u'&MMSD GIS')

        self.menu = None
        self.menugc = QMenu(self.iface.mainWindow())
        self.menugc.setObjectName(u'adaptainfra_menu')
        self.menugc.setTitle(u'ADAPTAINFRA')
        self.menuBar = self.iface.mainWindow().menuBar()
        self.menuBar.insertMenu(self.iface.firstRightStandardMenu().menuAction(), self.menugc)

        #self.menuLogButton = self.createToolButton(self.toolbar, u'LOGIN', False)
        self.menuGeosustentabilityButton = self.createToolButton(self.toolbar, u'GEOSUSTENTABILITY', False)

        icon_path_geosustentability = ':/plugins/adaptainfra/icons/geosustentability_icon.png'
        self.action_geosustentability = self.add_action(
            icon_path_geosustentability,
            text=u'GEOSUSTENTABILITY',
            callback=self.run_geosustentability,
            # add_to_menu=False,
            add_to_toolbar=False,
            # withShortcut=False,
            parentToolbar=self.menugc,
            isCheckable=False
        )
        self.menuGeosustentabilityButton.addAction(self.action_geosustentability)
        self.menuGeosustentabilityButton.setDefaultAction(self.action_geosustentability)


        self.toolbar.addSeparator()

        self.label_links = QLabel("Links úteis -> ")
        self.label_links.setStyleSheet("""
            QLabel {
                color: black;
                font-weight: normal;
                padding-left: 5px;
                padding-right: 5px;
            }
        """)
        self.toolbar.addWidget(self.label_links)


        #botão fundo de inovação
        icon_path_fundo = os.path.join(self.plugin_dir, "icons", "logo_fia.png")
        icon_fundo = QIcon(icon_path_fundo)
        self.action_fundo = QAction(icon_fundo, "Fundo de Inovação", self.toolbar)
        self.action_fundo.triggered.connect(self.openfundo)
        self.toolbar.addAction(self.action_fundo)

        #botao olasis
        icon_path_olasis = os.path.join(self.plugin_dir, "icons", "olabot_icon_semfundo.png")
        icon_olasis = QIcon(icon_path_olasis)
        self.action_olasis = QAction(icon_olasis, "Olasis", self.toolbar)
        self.action_olasis.triggered.connect(self.openolasis)
        self.toolbar.addAction(self.action_olasis)

        #botao justiça climática
        icon_path_justica_climatica = os.path.join(self.plugin_dir, "icons", "justica_climatica_logo_semfundo.png")
        icon_justica_climatica = QIcon(icon_path_justica_climatica)
        self.action_justica_climatica = QAction(icon_justica_climatica, "Justiça climática", self.toolbar)
        self.action_justica_climatica.triggered.connect(self.openjusticaclimatica)
        self.toolbar.addAction(self.action_justica_climatica)

        self.toolbar.addSeparator()
        #self.menuROSButton = self.createToolButton(self.toolbar, u'ROS', False)
        #logo Mix

        self.label_language = QLabel("Language -> ")
        self.label_language.setStyleSheet("""
            QLabel {
                color: black;
                font-weight: normal;
                padding-left: 5px;
                padding-right: 5px;
            }
        """)
        self.toolbar.addWidget(self.label_language)


        # Cria o ComboBox
        self.language_combo = QComboBox()
        # Adiciona os idiomas
        self.language_combo.addItems([
            "PT",
            "EN",
            "ES"
        ])
        # Define o idioma padrão (PT)
        self.language_combo.setCurrentText("PT")
    
        self.language_combo.currentTextChanged.connect(self.run_translate)
        # Adiciona na barra de ferramentas
        self.language_combo_action = self.toolbar.addWidget(self.language_combo)


        self.toolbar.addSeparator()


        self.label_sobre = QLabel("Desenvolvido por -> ")
        self.label_sobre.setStyleSheet("""
            QLabel {
                color: black;
                font-weight: normal;
                padding-left: 5px;
                padding-right: 5px;
            }
        """)
        self.toolbar.addWidget(self.label_sobre)
        

        #botão adaptainfra
        icon_path_adaptainfra = os.path.join(self.plugin_dir, "icons", "icon_adaptainfra_semfundo.png")
        icon_adaptainfra = QIcon(icon_path_adaptainfra)
        self.action_adaptainfra = QAction(icon_adaptainfra, "Adaptainfra", self.toolbar)
        self.action_adaptainfra.triggered.connect(self.openadaptainfra)
        self.toolbar.addAction(self.action_adaptainfra)
        #botão giz
        icon_path_giz = os.path.join(self.plugin_dir, "icons", "giz_icon.png")
        icon_giz = QIcon(icon_path_giz)
        self.action_giz = QAction(icon_giz, "Giz Site", self.toolbar)
        self.action_giz.triggered.connect(self.opengiz)
        self.toolbar.addAction(self.action_giz)
        #botão mix
        icon_path = os.path.join(self.plugin_dir, "icons", "mix_logo.jpeg")
        icon = QIcon(icon_path)
        self.action = QAction(icon, "Sobre site", self.toolbar)
        self.action.triggered.connect(self.openMixgeo)
        self.toolbar.addAction(self.action)


        
        
        

        

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MIXGEO', message)

    def createToolButton(self, parent, text, setpop=True):
        """
        Creates a tool button (pop up menu)
        """
        button = QToolButton(parent)
        button.setObjectName(text)
        button.setToolButtonStyle(Qt.ToolButtonIconOnly)
        if setpop:
            button.setPopupMode(QToolButton.MenuButtonPopup)
        parent.addWidget(button)
        self.actions.append(button)
        return button

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        #add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
        parentMenu = None,
        withShortcut=False,
        tooltip = None,
        parentToolbar = None,
        parentButton = None,
        isCheckable = False):
        """Add a toolbar icon to the InaSAFE toolbar.
        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str
        :param text: Text that should be shown in menu items for this action.
        :type text: str
        :param callback: Function to be called when the action is triggered.
        :type callback: function
        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool
        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool
        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool
        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str
        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget
        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.
        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.toolbar.addAction(action)
        #if add_to_menu:##
            #self.menu.addAction(action)
        if parentMenu:
            parentMenu.addAction(action)
        if withShortcut:
            self.iface.registerMainWindowAction(action, '')
        if isCheckable:
            action.setCheckable(True)
        if tooltip:
            action.setToolTip(tooltip)
        if parentToolbar:
            parentToolbar.addAction(action)
        if parentButton:
            parentButton.addAction(action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        for action in self.actions:
            try:
                self.iface.removePluginMenu(
                    "gctools_menu",
                    action)
                self.iface.removeToolBarIcon(action)
                self.iface.unregisterMainWindowAction(action)
            except:
                pass
        if self.menugc is not None:
            self.menuBar.removeAction(self.menugc.menuAction())
        del self.menugc
        del self.toolbar

    def openjusticaclimatica(self):
        QDesktopServices.openUrl(QUrl("https://olacefs-justica-climatica.onrender.com/"))

    def openolasis(self):
        QDesktopServices.openUrl(QUrl("https://adaptainfra.streamlit.app/"))

    def openfundo(self):
        QDesktopServices.openUrl(QUrl("https://fondodeinovacionadaptainfra.grantplatform.com/"))

    def openadaptainfra(self):
        QDesktopServices.openUrl(QUrl("https://olacefs.com/giz/pt/"))

    def openMixgeo(self):
        QDesktopServices.openUrl(QUrl("https://www.clubinhox.com.br/adaptainfra"))

    def opengiz(self):
        QDesktopServices.openUrl(QUrl("https://www.giz.de/en/pt-br/brasil"))
   
    def run_geosustentability(self):
        self.geosustentability = GEOSUSTENTABILITY(self.iface,self)
        self.geosustentability.run()
    
    def translate_module(self):
        self.translate = TRANSLATE(self.iface,self)

    def run_translate(self):
        self.translate.run()
        print("teste")

    def signal_worker(self,data):
        print("teste_signal",data)

    def start_worker(self):
        print("loggin") #
        self.worker = Worker(self.plugin_dir,self.iface)
        self.worker.stp = False
        self.worker.up_list.connect(self.signal_worker)
        self.worker.start()


    def stop_worker(self):
        print("stopped loggin")
        self.worker.stp = True

    