# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GEO SUSTENTABILITY=
                                 A QGIS plugin
 Geo Sustentability no Qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-08
        git sha              : $Format:%H$
        copyright            : Mateus Melo Siqueira/GIZ

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""##
import os
import sys 
sys.path.append(os.path.join(os.path.dirname(__file__),'lib'))
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant, QTimer
from qgis.PyQt.QtGui import QIcon, QColor, QPixmap
from qgis.PyQt.QtWidgets import QMessageBox,QWidget, QDockWidget, QAction, QFileDialog, QTableWidget, QTableWidgetItem, QGridLayout, QDialog, QPushButton, QProgressBar
#from PyQt5.QtCore import  Qt, QSize, QVariant
from qgis.core import QgsVectorLayer,QgsRasterLayer, QgsRectangle, QgsVectorFileWriter, QgsGeometry,QgsFields, QgsField, QgsFeature, QgsProject
from qgis.PyQt.QtCore import Qt, QSize, QVariant
# Initialize Qt resources from file resources.py
#from .resources import *
# Import the code for the dialog#
from qgis.core import QgsExpressionContextUtils, QgsProject
from qgis.core import QgsVectorFileWriter
from datetime import datetime
import os.path

from osgeo import gdal
# import gdal
from qgis.core import *
from qgis.gui import *
from qgis.utils import *
from osgeo import osr
from PyQt5.QtCore import QThread, pyqtSignal
import pathlib
from pathlib import Path
pathlib.PosixPath = pathlib.WindowsPath
# import osr
import multiprocessing

class Worker(QThread):
    def __init__(self, plugin_dir):
        QThread.__init__(self)
        self.stp = False
        self.plugin_dir = plugin_dir


    results = pyqtSignal(list)
    
    def updateSignals(self):
        self.results.emit([0,0])
    


    def run(self):
        pass

    

class TRANSLATE:
    def __init__(self, iface, cls_main):

        # Save reference to the QGIS interface
        self.adaptainfra = cls_main
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = self.adaptainfra.plugin_dir
        self.db = None



        


        #QgsExpressionContextUtils.setGlobalVariable( 'aigis_status',50)
    def setworker(self):

        

        #set Worker Thread
        self.worker= Worker(self.plugin_dir,
                                                 weight,
                                                 self.file_folder_status,
                                                 dirs,
                                                 images,
                                                 img_size,
                                                 is_slice,
                                                 confidence,
                                                 overlap,
                                                 is_pontos,
                                                 is_poligonos,
                                                 self.db,
                                                 self.id_proc,
                                                 status )

        self.worker.up_list.connect(self.updateBar)
 
        self.worker.run()

    def updateBar(self):
        pass

    def dir_file(self):
        self.file_folder_status = 1
        self.img_dir = QFileDialog.getOpenFileName()[0]
        self.dlg.line_file.setText(self.img_dir)
        print(self.img_dir)

    def dir_folder(self):
        self.file_folder_status = 0
        #self.img_dir = QFileDialog.getExistingDirectory()

        filenames, _ = QFileDialog.getOpenFileNames(
                                                    None,
                                                    "QFileDialog.getOpenFileNames()",
                                                    "",
                                                    "Tiff (*.tif);;All Files (*);",)
        if filenames:
            self.img_dir = os.path.dirname(filenames[0])
            self.dlg.line_file.setText(self.img_dir)
            #fill table
            images = [os.path.basename(x) for x in filenames]
            
    def translate_toolbar(self):
        if self.adaptainfra.language_combo.currentText()=='PT':
            self.adaptainfra.label_links.setText("Links úteis -> ")
            self.adaptainfra.label_language.setText("Linguagem -> ")
            self.adaptainfra.label_sobre.setText("Desenvolvido por -> ")
            self.adaptainfra.action_fundo.setText("Fundo de Inovação")
            self.adaptainfra.action_justica_climatica.setText("Justiça climática")
        elif self.adaptainfra.language_combo.currentText()=='EN':
            self.adaptainfra.label_links.setText("Useful links -> ")
            self.adaptainfra.label_language.setText("Language -> ")
            self.adaptainfra.label_sobre.setText("Developed by -> ")
            self.adaptainfra.action_fundo.setText("Inovation Fund")
            self.adaptainfra.action_justica_climatica.setText("Climate Justice")
        elif self.adaptainfra.language_combo.currentText()=='ES':
            self.adaptainfra.label_links.setText("Enlaces uteis -> ")
            self.adaptainfra.label_language.setText("Lenguaje -> ")
            self.adaptainfra.label_sobre.setText("Desarrollado por -> ")
            self.adaptainfra.action_fundo.setText("Foundo de Innovación")
            self.adaptainfra.action_justica_climatica.setText("Justicia Climática")
    
    def run(self):
        #self.dlg = GEOSUSTENTABILITYDialog()
        self.file_folder_status = None
        # show the dialog
        #self.dlg.show()
        #self.dlg.closeEvent = self.CloseEvent

        self.translate_toolbar()