# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GEO SUSTENTABILITY
                                 A QGIS plugin
 Geo Sustentability no Qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-08
        git sha              : $Format:%H$
        copyright            : Mateus Melo Siqueira/GIZ

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""##
import os
import sys 
sys.path.append(os.path.join(os.path.dirname(__file__),'lib'))
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant, QTimer
from qgis.PyQt.QtGui import QIcon, QColor, QPixmap, QMovie 
from qgis.PyQt.QtWidgets import QApplication, QComboBox, QSizePolicy, QMessageBox,QWidget, QLabel, QDockWidget, QAction, QFileDialog, QTableWidget, QTableWidgetItem, QGridLayout, QVBoxLayout, QDialog, QPushButton, QProgressBar
#from PyQt5.QtCore import  Qt, QSize, QVariant
from qgis.core import QgsVectorLayer,QgsRasterLayer, QgsRectangle, QgsVectorFileWriter, QgsGeometry,QgsFields, QgsField, QgsFeature, QgsProject, QgsTask, QgsApplication
from qgis.PyQt.QtCore import Qt, QSize, QVariant

# Initialize Qt resources from file resources.py
#from .resources import *
# Import the code for the dialog#
#from .geosustentability_dialog import GEOSUSTENTABILITYDialog
from qgis.core import QgsExpressionContextUtils, QgsProject, QgsDataSourceUri
from qgis.core import QgsVectorFileWriter
from datetime import datetime
import os.path

from osgeo import gdal
# import gdal
from qgis.core import *
from qgis.gui import *
from qgis.utils import *
from osgeo import osr
from PyQt5.QtCore import QThread, pyqtSignal
import pathlib
from pathlib import Path
pathlib.PosixPath = pathlib.WindowsPath
# import osr
import multiprocessing
from qgis.core import QgsExpression

from qgis.core import QgsTask, QgsApplication



class LoadingDialog(QDialog):

    def __init__(self, parent=None):
        super().__init__(parent)

        self.setWindowTitle("Carregando")
        self.setWindowFlags(
            Qt.Dialog |
            Qt.CustomizeWindowHint |
            Qt.WindowTitleHint |
            Qt.WindowCloseButtonHint
        )

        self.setModal(False)
        self.setFixedSize(220, 140)

        layout = QVBoxLayout()

        self.labelGif = QLabel()
        self.labelGif.setAlignment(Qt.AlignCenter)

        self.movie = QMovie(":/images/themes/default/mIconLoading.gif")
        self.labelGif.setMovie(self.movie)

        self.labelTexto = QLabel("Carregando camadas...")
        self.labelTexto.setAlignment(Qt.AlignCenter)

        layout.addWidget(self.labelGif)
        layout.addWidget(self.labelTexto)

        self.setLayout(layout)

    def showEvent(self, event):
        self.movie.start()
        super().showEvent(event)

    def closeEvent(self, event):
        self.movie.stop()
        super().closeEvent(event)

class CarregarCamadasTask(QgsTask):

    def __init__(self, plugin, schema, tabela, nome):
        super().__init__("Carregando camadas", QgsTask.CanCancel)
        self.plugin = plugin
        self.schema = schema
        self.tabela = tabela
        self.nome = nome

    def run(self):
        # processamento pesado
        self.plugin.adicionar_camada(self.schema, self.tabela, self.nome)
        return True

    def finished(self, result):
        self.plugin.loading.close()

  


class ImageLabel(QLabel):

    def __init__(self, image):
        super().__init__()

        self.original = QPixmap(image)

        self.setSizePolicy(
            QSizePolicy.Expanding,
            QSizePolicy.Expanding
        )

        self.setMinimumSize(1, 1)

    def resizeEvent(self, event):

        if not self.original.isNull():

            self.setPixmap(
                self.original.scaled(
                    self.size(),
                    Qt.KeepAspectRatio,
                    Qt.SmoothTransformation
                )
            )

        super().resizeEvent(event)


class Worker(QThread):
    def __init__(self, plugin_dir):
        QThread.__init__(self)
        self.stp = False
        self.plugin_dir = plugin_dir


    results = pyqtSignal(list)
    
    def updateSignals(self):
        self.results.emit([0,0])
    


    def run(self):
        pass

    

class GEOSUSTENTABILITY:
    def __init__(self, iface, cls_main):

        # Save reference to the QGIS interface
        self.adaptainfra = cls_main
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = self.adaptainfra.plugin_dir
        self.db = None
    
        self.host = "clubinhox0.ddns.net"   # host
        #self.host = "192.168.1.200"
        self.port = "5432"           # porta
        self.db = "adaptainfra"        # banco
        self.user = "adaptainfra"       # usuário
        self.password = "adaptainfra@@"            # senha
        
        


        #QgsExpressionContextUtils.setGlobalVariable( 'aigis_status',50)
    def setworker(self):

        

        #set Worker Thread
        self.worker= Worker(self.plugin_dir,
                                                 weight,
                                                 self.file_folder_status,
                                                 dirs,
                                                 images,
                                                 img_size,
                                                 is_slice,
                                                 confidence,
                                                 overlap,
                                                 is_pontos,
                                                 is_poligonos,
                                                 self.db,
                                                 self.id_proc,
                                                 status )

        self.worker.up_list.connect(self.updateBar)
 
        self.worker.run()

    def updateBar(self):
        pass

    def dir_file(self):
        self.file_folder_status = 1
        self.img_dir = QFileDialog.getOpenFileName()[0]
        self.dlg.line_file.setText(self.img_dir)
        print(self.img_dir)

    def dir_folder(self):
        self.file_folder_status = 0
        #self.img_dir = QFileDialog.getExistingDirectory()

        filenames, _ = QFileDialog.getOpenFileNames(
                                                    None,
                                                    "QFileDialog.getOpenFileNames()",
                                                    "",
                                                    "Tiff (*.tif);;All Files (*);",)
        if filenames:
            self.img_dir = os.path.dirname(filenames[0])
            self.dlg.line_file.setText(self.img_dir)
            #fill table
            images = [os.path.basename(x) for x in filenames]
            
    

    
    def run(self):
        #self.dlg = GEOSUSTENTABILITYDialog()
        self.file_folder_status = None
        # show the dialog
        #self.dlg.show()
        #self.dlg.closeEvent = self.CloseEvent

        self.canvas = self.iface.mapCanvas()
        self.dock_gc = QDockWidget()

        # Run the dialog event loop
        self.dock_gc.setObjectName('Geo Sustentability')
        self.dock_gc.setWindowTitle('Geo Sustentability')

        self.dock_gc.setAllowedAreas(Qt.RightDockWidgetArea)
        self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dock_gc)

        self.layout = QVBoxLayout()

        
        #Imagem painel do Geo Sustentability
        self.label_geosustentability = ImageLabel(os.path.join(self.plugin_dir, "images", "geosustentability_image.png"))
        self.layout.addWidget(self.label_geosustentability)
        
        self.label_contexto = QLabel("Contexto de análise")
        self.layout.addWidget(self.label_contexto)

        self.cb_contexto = QComboBox()
        self.lista_contextos = ['Selecione um contexto','Brazil','America Latina Caribe','Amazonia']
        self.cb_contexto.insertItems(0,self.lista_contextos)
        self.cb_contexto.setCurrentText('Selecione um contexto')
        self.cb_contexto.currentTextChanged.connect(self.get_camadas)
        self.layout.addWidget(self.cb_contexto)

        self.label_elemento = QLabel("Selecione uma rodovia")
        self.layout.addWidget(self.label_elemento)

        self.cb_elemento = QComboBox()
        self.cb_elemento.insertItems(0,['Selecione um elemento'])
        self.cb_elemento.currentTextChanged.connect(self.filtrarCamada)
        self.layout.addWidget(self.cb_elemento)

        self.layout.addStretch()







        self.wd = QWidget()
        self.wd.setLayout(self.layout)
        self.dock_gc.setWidget(self.wd)
    
    def deletar_camadas(self):
        QgsProject.instance().removeAllMapLayers()

    def trazer_hybrid(self):

        url = (
    "type=xyz&"
    "url=https://server.arcgisonline.com/ArcGIS/rest/services/"
    "World_Imagery/MapServer/tile/{z}/{y}/{x}"
        )

        layer = QgsRasterLayer(url, "Esri World Imagery", "wms")

        if layer.isValid():
            QgsProject.instance().addMapLayer(layer)
        else:
            print(layer.error().summary())


    def get_camadas(self):
        self.deletar_camadas()
        self.loading = LoadingDialog(self.iface.mainWindow())
        self.canvas = self.iface.mapCanvas()
        self.canvas.renderStarting.connect(self.render_iniciou)
        self.canvas.renderComplete.connect(self.render_finalizado)

        if self.cb_contexto.currentText() == 'Brazil':
            print("trazer brazil")
            self.trazer_hybrid()
            estilo_brasil_dir = os.path.join(self.plugin_dir,"estilos","limite_brasil.qml")
            self.adicionar_camada("public","BR_Pais_2025", "Limite Brasil", estilo_brasil_dir)

            estilo_ucs_brasil_dir = os.path.join(self.plugin_dir,"estilos", "ucs_brasil.qml")
            self.adicionar_camada("public","ucs_brasil", "Áreas protegidas", estilo_ucs_brasil_dir)

            estilo_municipios_dir = os.path.join(self.plugin_dir, "estilos", "municipios.qml")
            self.adicionar_camada("public", "municipios_br", "Municipios", estilo_municipios_dir)

            
            estilo_rodovias_brasil_dir = os.path.join(self.plugin_dir,"estilos","rodovias_brasil.qml")
            self.adicionar_camada("public","snv_202507a","Rodovias SNV", estilo_rodovias_brasil_dir)
            estilo_rodovias_brasil_buffer_dir = os.path.join(self.plugin_dir,"estilos","rodovias_brasil_buffer.qml")
            self.adicionar_camada("public","rodovias_buffer_dissolve_br","Rodovias SNV Buffer 40KM", estilo_rodovias_brasil_buffer_dir)

            

            #zoom
            layer = QgsProject.instance().mapLayersByName("Limite Brasil")[0]
            iface.mapCanvas().setExtent(layer.extent())
            iface.mapCanvas().refresh()
            
            layer = QgsProject.instance().mapLayersByName("Rodovias SNV")[0]

            self.cb_elemento.blockSignals(True)
            self.cb_elemento.clear()
            
            rodovias = []
            for feat in layer.getFeatures():
                if feat['vl_br'] not in rodovias:
                    rodovias.append(str(feat['vl_br']))
            rodovias_sorted = ['Selecione o elemento'] + sorted(rodovias)
                
            self.cb_elemento.insertItems(0,rodovias_sorted)
            self.cb_elemento.blockSignals(False)

        if self.cb_contexto.currentText() == 'America Latina Caribe':
            print("trazer America Latina Caribe")
            #task = CarregarCamadasTask(...)
            #QgsApplication.taskManager().addTask(task)  
            self.trazer_hybrid()
            estilo_limite_america_latina_caribe_dir = os.path.join(self.plugin_dir, "estilos", "limite_america_latina_caribe.qml")
            self.adicionar_camada("public", "limite_america_latina_caribe", "Limite America Latina Caribe", estilo_limite_america_latina_caribe_dir)
            estilo_ucs_america_caribe_dir = os.path.join(self.plugin_dir,"estilos","ucs_brasil.qml")
            self.adicionar_camada("public","ucs_america_latina_caribe_geom", "Áreas protegidas", estilo_ucs_america_caribe_dir)
            #zoom
            layer = QgsProject.instance().mapLayersByName("Limite America Latina Caribe")[0]
            iface.mapCanvas().setExtent(layer.extent())
            iface.mapCanvas().refresh()
            #self.loading.close()
        if self.cb_contexto.currentText() == 'Amazonia':
            print("trazer Amazonia")
            self.trazer_hybrid()
            estilo_limite_amazonia_dir = os.path.join(self.plugin_dir,"estilos","limite_amazonia.qml")
            self.adicionar_camada("public","Limites_Amazonia_Legal_2024", "Limite Amazonia Legal", estilo_limite_amazonia_dir)
            estilo_ucs_amazonia_dir = os.path.join(self.plugin_dir,"estilos", "ucs_amazonia.qml")
            self.adicionar_camada("public","ucs_amazonia_indimapa", "Áreas protegidas", estilo_ucs_amazonia_dir)
            estilo_rodovias_amazonia = os.path.join(self.plugin_dir,"estilos","rodovias_amazonia.qml")
            self.adicionar_camada("public","snv_202507_amazonia","Rodovias SNV", estilo_rodovias_amazonia)
            estilo_rodovias_amazonia_buffer_dir = os.path.join(self.plugin_dir,"estilos","rodovias_amazonia_buffer.qml")
            self.adicionar_camada("public","snv_202507_amazonia_buffer","Rodovias SNV Buffer 40KM", estilo_rodovias_amazonia_buffer_dir)
            #zoom
            layer = QgsProject.instance().mapLayersByName("Limite Amazonia Legal")[0]
            iface.mapCanvas().setExtent(layer.extent())
            iface.mapCanvas().refresh()
        

    def filtrarCamada(self):
        print("Filtrando camada")
        layer_rod = QgsProject.instance().mapLayersByName("Rodovias SNV Buffer 40KM")[0]
        layer_mun = QgsProject.instance().mapLayersByName("Municipios")[0]
        layer_mun.setSubsetString("")
        layer_rod.setSubsetString("")

        if self.cb_contexto.currentText() == 'Brazil':
            self.render_iniciou()
            self.canvas.renderComplete.connect(self.render_finalizado2)
            
            print("elemento do brazil")
            layer = QgsProject.instance().mapLayersByName("Rodovias SNV")[0]
            layer.setSubsetString(f'"vl_br" = \'{self.cb_elemento.currentText()}\'')

            layer_rod.setSubsetString(f'"vl_br" = \'{self.cb_elemento.currentText()}\'')

            

            muns = []
            for feat_rod in layer_rod.getFeatures():
                for feat_mun in layer_mun.getFeatures():
                    if feat_rod.geometry().intersects(feat_mun.geometry()):
                        muns.append(feat_mun['NM_MUNICIP'])

            valores = ",".join(
                    QgsExpression.quotedString(str(mun))
                    for mun in muns
                    )

            layer_mun.setSubsetString(
                f'"NM_MUNICIP" IN ({valores})'
            )

            iface.mapCanvas().setExtent(layer_rod.extent())
            iface.mapCanvas().refresh()

            


    def adicionar_camada(self, schema, tabela, nome, estilo):

        uri = QgsDataSourceUri()

        uri.setConnection(
            self.host,
            self.port,
            self.db,
            self.user,
            self.password
        )

        uri.setDataSource(
            schema,
            tabela,
            "geom",
            "",
            "id"
        )
    
        layer = QgsVectorLayer(uri.uri(False), nome, "postgres")


        if layer.isValid():
            QgsProject.instance().addMapLayer(layer)
        else:
            print(f"Erro ao carregar {nome}")

        layer.loadNamedStyle(estilo)
        layer.triggerRepaint()
        iface.layerTreeView().refreshLayerSymbology(layer.id())


    def render_iniciou(self):
        self.loading.show()

    def render_finalizado(self):
        self.loading.close()
        
        self.canvas.renderStarting.disconnect(self.render_iniciou)
        self.canvas.renderComplete.disconnect(self.render_finalizado)
        
    def render_finalizado2(self):
        self.loading.close()
        self.canvas.renderComplete.disconnect(self.render_finalizado2)
        